### ISSUE TITLE
jupyter's python3 kernel seems to fail with Python 3.9 and 3.10 (Exception 'coroutine' object is not subscriptable)

### ISSUE THREAD

**Issue by certik** [conda-forge/jupyter-feedstock#23]
Steps to reproduce:
```bash
conda create -n lf4 -c conda-forge jupyter python=3.9
conda activate lf4
jupyter console --kernel="python3"
```
Then in the jupyter console:
```console
$ jupyter console --kernel="python3"
Jupyter console 6.4.0

Python 3.9.9 | packaged by conda-forge | (main, Dec 20 2021, 02:41:06) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.30.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: 4/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/site-packages/jupyter_console/ptshell.py:852: RuntimeWarning: coroutine 'ZMQSocketChannel.msg_ready' was never awaited
  while self.client.iopub_channel.msg_ready():
RuntimeWarning: Enable tracemalloc to get the object allocation traceback

Unhandled exception in event loop:
  File "/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/site-packages/prompt_toolkit/input/vt100.py", line 170, in callback_wrapper
    callback()
  File "/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/site-packages/prompt_toolkit/application/application.py", line 690, in read_from_input
    self.key_processor.process_keys()
  File "/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/site-packages/prompt_toolkit/key_binding/key_processor.py", line 271, in process_keys
    self._process_coroutine.send(key_press)
  File "/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/site-packages/prompt_toolkit/key_binding/key_processor.py", line 186, in _process
    self._call_handler(matches[-1], key_sequence=buffer[:])
  File "/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/site-packages/prompt_toolkit/key_binding/key_processor.py", line 321, in _call_handler
    handler.call(event)
  File "/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/site-packages/prompt_toolkit/key_binding/key_bindings.py", line 124, in call
    result = self.handler(event)
  File "/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/site-packages/jupyter_console/ptshell.py", line 475, in _
    self.handle_iopub()
  File "/Users/ondrej/mambaforge/envs/lf4/lib/python3.9/site-packages/jupyter_console/ptshell.py", line 854, in handle_iopub
    msg_type = sub_msg['header']['msg_type']

Exception 'coroutine' object is not subscriptable
Press ENTER to continue...
```

This works with `python=3.8`. Originally reported at: https://fortran-lang.discourse.group/t/i-have-problem-with-lfortran-installation/2440/7

I am on Apple M1, but the original report was on Windows WSL.

**Comment by xylar** [comment]
I presume this issue has been addressed elsewhere as there was no follow-up here.  I'll close it on that assumption.  If there is an ongoing problem, it would be best to open a new issue.

**Comment by certik** [comment]
The above error is still there. But for old Python, so let's not worry about it I guess.

**Comment by xylar** [comment]
@certik, if you still see this issue for old python, it should be reported here:
https://github.com/jupyter/jupyter_console/issues
or perhaps here if it is conda-forge specific:
https://github.com/conda-forge/jupyter_console-feedstock

This feedstock is just a metapackage for various other jupyter packages and the fix would not happen here.
